version: 2.1

orbs:
  node: circleci/node@5.0.2
  azure-acr: circleci/azure-acr@0.2.0

workflows:
  test-build-push-image:
    jobs:
      - node/test:
          test-results-for: jest
      - azure-acr/build-and-push-image:
          login-server-name: devopsupskillregistrymlckk.azurecr.io
          registry-name: devopsupskillregistrymlckk
          repo: devops-bookstore-frontend
          tag: "1.$CIRCLE_BUILD_NUM"
          requires:
            - "node/test"
